ModuleNotFoundError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).
Traceback:
File "/mount/src/data_ingestion/streamlit_app.py", line 10, in <module>
    from app.sql_router import sql_programs, sql_academic_fees
File "/mount/src/data_ingestion/app.py", line 6, in <module>
    import google.generativeai as genai
